version: '3.8'
services:
  fastapi:
    build:
      context: .
      dockerfile: _docker/python/Dockerfile
    volumes:
      - .:/app
      - bash-data:/root/.local/bin
      - python-lib-data:/usr/local/lib/python3.10
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./_docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'fastapi_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3334:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  mysql-data:
  redis-data:
  bash-data:
  python-lib-data:
