"""2024_4_15_11_52_create_locations

Revision ID: 4bdee61ed04d
Revises: b314e6e8c4e9
Create Date: 2024-04-15 02:57:07.206176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel           
import geoalchemy2.types  


# revision identifiers, used by Alembic.
revision: str = '4bdee61ed04d'
down_revision: Union[str, None] = 'b314e6e8c4e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('uuid', sa.String(length=36), nullable=False, comment='UUID'),
    sa.Column('lat', sa.Numeric(precision=10, scale=8), nullable=False, comment='緯度'),
    sa.Column('lng', sa.Numeric(precision=11, scale=8), nullable=False, comment='経度'),
    sa.Column('point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False, comment='位置情報'),
    sa.Column('geo_hash', sa.String(length=12), nullable=False, comment='ジオハッシュ'),
    sa.Column('srid', sa.String(length=10), nullable=False, comment='SRID'),
    sa.Column('save_datetime', sa.TIMESTAMP(timezone=True), nullable=True, comment='保存日時'),
    sa.Column('country', sa.String(length=100), nullable=True, comment='国'),
    sa.Column('administrative_area', sa.String(length=100), nullable=True, comment='都道府県'),
    sa.Column('sub_administrative_area', sa.String(length=100), nullable=True, comment='市区町村(日本は無い場合が多い)'),
    sa.Column('locality', sa.String(length=100), nullable=True, comment='市区町村'),
    sa.Column('sub_locality', sa.String(length=100), nullable=True, comment='町名(日本は無い場合が多い)'),
    sa.Column('postal_code', sa.String(length=100), nullable=True, comment='郵便番号'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='地名'),
    sa.Column('street', sa.String(length=100), nullable=True, comment='住所'),
    sa.Column('iso_country_code', sa.String(length=10), nullable=True, comment='ISO国コード'),
    sa.Column('thoroughfare', sa.String(length=100), nullable=True, comment='通り'),
    sa.Column('sub_thoroughfare', sa.String(length=100), nullable=True, comment='番地'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_locations_point', 'locations', ['point'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_locations_point', table_name='locations', postgresql_using='gist')
    op.drop_table('locations')
    # ### end Alembic commands ###
