"""2024_4_16_16_33_change_hashtags

Revision ID: 50224de85470
Revises: a05571e03661
Create Date: 2024-05-07 00:37:50.478171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision: str = '50224de85470'
down_revision: Union[str, None] = 'a05571e03661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'hash_tags', ['tag'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hash_tags', type_='unique')
    # ### end Alembic commands ###
