"""create_change_timestamp

Revision ID: 5c3fa0bfa365
Revises: 
Create Date: 2024-03-14 14:31:57.434573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision: str = '5c3fa0bfa365'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('uuid', sa.String(length=36), nullable=False, comment='UUID'),
    sa.Column('account_name', sa.String(length=100), nullable=False, comment='アカウント名'),
    sa.Column('id_account', sa.String(length=100), nullable=False, comment='アカウントID'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='メールアドレス'),
    sa.Column('hashed_password', sa.String(length=100), nullable=False, comment='パスワード'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='アクティブフラグ True:ログイン中 False:ログアウト中'),
    sa.Column('birth_date', sa.Date(), nullable=False, comment='生年月日'),
    sa.Column('other_user_invitation_code', sa.String(length=36), nullable=True, comment='他ユーザー招待コード'),
    sa.Column('refresh_token', sa.String(length=100), nullable=True, comment='リフレッシュトークン'),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='リフレッシュトークン有効期限'),
    sa.Column('email_verified', sa.Boolean(), nullable=False, comment='メール認証フラグ True:認証済 False:未認証'),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='削除日時とフラグ'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_account'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('email_verifications',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ユーザーID'),
    sa.Column('email_verified_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='メール認証日時'),
    sa.Column('email_verify_token', sa.String(length=100), nullable=True, comment='メール認証トークン'),
    sa.Column('email_verified_expired_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='メール認証有効期限'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_verifications')
    op.drop_table('users')
    # ### end Alembic commands ###
