"""create_email_verifications

Revision ID: 80bbbe1d7643
Revises: aabe030448a4
Create Date: 2024-02-24 15:40:40.438387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision: str = '80bbbe1d7643'
down_revision: Union[str, None] = 'aabe030448a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verifications',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ユーザーID'),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True, comment='メール認証日時'),
    sa.Column('email_verify_token', sa.String(length=100), nullable=True, comment='メール認証トークン'),
    sa.Column('email_verified_expired_at', sa.DateTime(), nullable=True, comment='メール認証有効期限'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False, comment='メール認証フラグ True:認証済 False:未認証'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    op.drop_table('email_verifications')
    # ### end Alembic commands ###
