"""2024_4_16_10_03_create_files

Revision ID: 8d3c179bbd1e
Revises: aaba3188962b
Create Date: 2024-04-16 01:00:25.191171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision: str = '8d3c179bbd1e'
down_revision: Union[str, None] = 'aaba3188962b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('uuid', sa.String(length=36), nullable=False, comment='UUID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='ファイル名'),
    sa.Column('path', sa.String(length=1024), nullable=False, comment='ファイルパス'),
    sa.Column('is_used', sa.Boolean(), nullable=False, comment='使用中フラグ False:未使用 True:使用中'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
