"""2024_4_16_16_33_change_users

Revision ID: a05571e03661
Revises: 8d3c179bbd1e
Create Date: 2024-04-16 07:32:04.836992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a05571e03661'
down_revision: Union[str, None] = '8d3c179bbd1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'files', ['image_id'], ['id'])
    op.drop_column('users', 'image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_path', mysql.VARCHAR(length=1024), nullable=True, comment='画像パス'))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'image_id')
    # ### end Alembic commands ###
