"""2024_4_15_12_03_create_post_images_and_hash_tag_posts

Revision ID: aaba3188962b
Revises: b2f8326baf40
Create Date: 2024-04-15 03:12:31.170281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision: str = 'aaba3188962b'
down_revision: Union[str, None] = 'b2f8326baf40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hash_tag_posts',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('post_id', sa.Integer(), nullable=False, comment='ユーザーID'),
    sa.Column('hash_tag_id', sa.Integer(), nullable=False, comment='ハッシュタグID'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hash_tag_id'], ['hash_tags.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hash_tag_posts')
    # ### end Alembic commands ###
