"""add_column_users

Revision ID: b23edcf6856b
Revises: 4b72a833bdc3
Create Date: 2024-04-04 08:51:24.090638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision: str = 'b23edcf6856b'
down_revision: Union[str, None] = '4b72a833bdc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile', sa.String(length=130), nullable=True, comment='プロフィール'))
    op.add_column('users', sa.Column('image_path', sa.String(length=1024), nullable=True, comment='画像パス'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_path')
    op.drop_column('users', 'profile')
    # ### end Alembic commands ###
