"""2024_4_15_12_03_create_posts_and_hash_tag

Revision ID: b2f8326baf40
Revises: c39731a520d8
Create Date: 2024-04-15 03:07:48.622760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision: str = 'b2f8326baf40'
down_revision: Union[str, None] = 'c39731a520d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hash_tags',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('tag', sa.String(length=100), nullable=False, comment='ハッシュタグ'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('uuid', sa.String(length=36), nullable=False, comment='UUID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ユーザーID'),
    sa.Column('location_id', sa.Integer(), nullable=False, comment='位置情報ID'),
    sa.Column('body', sa.Text(), nullable=False, comment='本文'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('post_images',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('post_id', sa.Integer(), nullable=False, comment='ユーザーID'),
    sa.Column('image_path', sa.String(length=1024), nullable=True, comment='画像パス'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_images')
    op.drop_table('posts')
    op.drop_table('hash_tags')
    # ### end Alembic commands ###
