"""add_column_users_link

Revision ID: b314e6e8c4e9
Revises: b23edcf6856b
Create Date: 2024-04-07 13:10:53.842802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision: str = 'b314e6e8c4e9'
down_revision: Union[str, None] = 'b23edcf6856b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('link', sa.String(length=1024), nullable=True, comment='リンク'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'link')
    # ### end Alembic commands ###
