"""2024_4_15_11_55_create_user_locationas

Revision ID: c39731a520d8
Revises: 4bdee61ed04d
Create Date: 2024-04-15 03:00:34.716023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             
import geoalchemy2.types


# revision identifiers, used by Alembic.
revision: str = 'c39731a520d8'
down_revision: Union[str, None] = '4bdee61ed04d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_locations',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('uuid', sa.String(length=36), nullable=False, comment='UUID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ユーザーID'),
    sa.Column('location_id', sa.Integer(), nullable=False, comment='位置情報ID'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_locations')
    # ### end Alembic commands ###
