"""users_add_email_verify

Revision ID: c3edd14fe92d
Revises: aabe030448a4
Create Date: 2024-02-23 14:50:15.501876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision: str = 'c3edd14fe92d'
down_revision: Union[str, None] = 'aabe030448a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False, comment='メール認証フラグ True:認証済 False:未認証'))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(), nullable=True, comment='メール認証日時'))
    op.add_column('users', sa.Column('email_verify_token', sa.String(length=100), nullable=True, comment='メール認証トークン'))
    op.add_column('users', sa.Column('email_verified_expired_at', sa.DateTime(), nullable=True, comment='メール認証有効期限'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified_expired_at')
    op.drop_column('users', 'email_verify_token')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
