FROM python:3.9 AS builder

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --user -r requirements.txt

COPY ./app /app

FROM python:3.9-slim

WORKDIR /app

COPY --from=builder /root/.local /root/.local
COPY ./app /app

ENV PATH=/root/.local:$PATH

EXPOSE 8000

# FastAPIサーバーの起動コマンド
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
